
- name: install openHAB runtime
  include: install_openhab_component.yml component=runtime

- name: install openHAB addons
  include: install_openhab_component.yml component=addons

#- name: install openHAB snapshot addons
#  include: install_openhab_snapshot_component.yml component=addons

- name: remove everything from the addons-folder
  shell: "rm {{ openhab_install_dir }}/runtime/{{openhab_version}}/addons/*"

#- name: link snapshot bindings into runtime
#  file: >
#    state=link
#    src={{ openhab_install_dir }}/addons/{{openhab_snapshot_version}}/org.openhab.{{ item }}-{{openhab_snapshot_version}}.jar
#    dest={{ openhab_install_dir }}/runtime/{{openhab_version}}/addons/org.openhab.{{ item }}-{{openhab_snapshot_version}}.jar
#  with_items:

- name: link bindings into runtime
  file: >
    state=link
    src={{ openhab_install_dir }}/addons/{{openhab_version}}/org.openhab.{{ item }}-{{openhab_version}}.jar
    dest={{ openhab_install_dir }}/runtime/{{openhab_version}}/addons/org.openhab.{{ item }}-{{openhab_version}}.jar
  with_items:
    - binding.http
    - binding.networkhealth
    - binding.ntp
    - binding.rfxcom
    - binding.samsungtv
    - binding.systeminfo
    - binding.plex
    - binding.denon
    - persistence.rrd4j
    - persistence.influxdb
    - action.pushover
    - binding.configadmin
    - binding.astro
    - binding.hue
    - binding.systeminfo
    - binding.samsungac
    - binding.weather
    - binding.exec

- name: install sigar
  include: install_sigar.yml

#- name: download my.openhab jar
#  get_url: >
#    url=https://bintray.com/artifact/download/openhab/mvn/org/openhab/io/org.openhab.io.myopenhab/{{openhab_version}}/org.openhab.io.myopenhab-{{openhab_version}}.jar
#    dest={{ openhab_install_dir }}/addons/{{openhab_version}}/
#    validate_certs=no

#- name: link to my.openhab jar
#  file: >
#    state=link
#    src={{ openhab_install_dir }}/addons/{{openhab_version}}/org.openhab.io.myopenhab-{{openhab_version}}.jar
#    dest={{ openhab_install_dir }}/runtime/{{openhab_version}}/addons/org.openhab.io.myopenhab-{{openhab_version}}.jar

- name: See if configurations is a directory (then we nuke it next)
  shell: "[ -d {{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations ] && echo 'Directory' || echo ''"
  register: is_directory

- name: delete example config directory
  file: path={{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations state=absent
  when: (is_directory.stdout)

- name: create openHAB configurations directory
  file: >
    state=directory
    path={{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations

- name: create openHAB configurations/items directory
  file: >
    state=directory
    path={{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations/items

- name: create openHAB configurations/persistence directory
  file: >
    state=directory
    path={{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations/persistence

- name: create openHAB configurations/transform directory
  file: >
    state=directory
    path={{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations/transform

- name: create openHAB configurations/rules directory
  file: >
    state=directory
    path={{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations/rules

- name: create openHAB configurations/scripts directory
  file: >
    state=directory
    path={{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations/scripts

- name: create openHAB configurations/sitemaps directory
  file: >
    state=directory
    path={{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations/sitemaps

- name: create openHAB configurations/templates directory
  file: >
    state=directory
    path={{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations/templates

- name: sync setup into config
  template: dest={{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations/{{item}} src=../templates/configurations/{{item}}
  with_items:
        - openhab.cfg
        - users.cfg
        - logback.xml
        - logback_debug.xml
        - items/huset.items
        - items/systeminfo.items
        - items/power.items
        - items/weather.items
        - items/floorHeating.items
        - items/roomba.items
        - items/alarm.items
        - items/speedtest.items
        - persistence/rrd4j.persist
        #- persistence/myopenhab.persist
        - persistence/influxdb.persist
        - rules/garage.rules
        - rules/heating.rules
        - rules/lights.rules
        - rules/proximity.rules
        - rules/security.rules
        - rules/status.rules
        - rules/modes.rules
        - rules/power.rules
        - rules/plex.rules
        - rules/weather.rules
        - rules/roomba.rules
        - rules/alarm.rules
        - rules/speedtest.rules
        - scripts/pushMessages.script
        - scripts/alarm-climate.js
        - scripts/alarm.js
        - sitemaps/huset.sitemap
        - sitemaps/panel.sitemap
        - transform/en.map
        - transform/getBasicOnOffState.js
        - transform/getLastUpdate.js
        - transform/getLastValue.js
        - transform/getLevelValue.js
        - transform/getPowerValue.js
        - transform/getValValue.js
        - transform/motion.map
        - transform/no.map
        - transform/floor.map
        - transform/alarm.map
        - transform/roomba.map
        - transform/roombaStatus.map

- name: sync alarm-api script into configurations
  copy: dest={{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations/scripts/alarm-api.js src=../templates/configurations/scripts/alarm-api.js

- name: create openHAB configurations/transform directory
  file: >
    state=directory
    path={{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations/transform

- name: sync transform setup into config
  copy: dest={{ openhab_install_dir }}/runtime/{{openhab_version}}/configurations/{{item}} src=../templates/configurations/{{item}}
  with_fileglob:
        - transform/*

- name: sync the weather-folder into webapps
  copy: dest={{ openhab_install_dir }}/runtime/{{openhab_version}}/webapps/ src=../files/weather-data

- name: create openHAB static directory
  file: >
    state=directory
    path={{ openhab_install_dir }}/runtime/{{openhab_version}}/webapps/static
  
- name: sync uuid setup into config
  template: src=webapps/static/uuid dest={{ openhab_install_dir }}/runtime/{{openhab_version}}/webapps/static/uuid

- name: sync secret setup into config
  template: src=webapps/static/secret dest={{ openhab_install_dir }}/runtime/{{openhab_version}}/webapps/static/secret

- name: copy start.sh
  template: src=start.sh dest={{ openhab_install_dir }}/runtime/{{openhab_version}}/start.sh mode=0752

- name: make sure the user is in the dialout group
  shell: "usermod -a -G dialout boss"
  sudo: yes

- name: link openhab into home folder
  file: >
    state=link
    src={{ openhab_install_dir }}/runtime/{{openhab_version}}
    dest={{ ansible_env.HOME }}/openhab

- name: create logs folder if it does not exist
  file: >
    state=directory
    path={{ openhab_install_dir }}/logs
    

- name: link logs folder
  file: >
    state=link
    src={{ openhab_install_dir }}/logs
    dest={{ openhab_install_dir }}/runtime/{{openhab_version}}/logs

- name: create rrd4j folder if it does not exist
  file: >
    state=directory
    path={{ openhab_install_dir }}/rrd4j

- name: link rr4dj folder
  file: >
    state=link
    src={{ openhab_install_dir }}/rrd4j
    dest={{ openhab_install_dir }}/runtime/{{openhab_version}}/etc/rrd4j

- name: link panel folder
  file: >
    state=link
    src={{ openhab_install_dir }}/panel
    dest={{ openhab_install_dir}}/runtime/{{openhab_version}}/webapps/panel

- name: copy openhab file to folder
  template: src=../files/openhab dest=/etc/init.d/openhab
  sudo: yes

- name: give it correct access rights
  shell: "chmod a+x /etc/init.d/openhab"
  sudo: yes

- name: Add the openhab to rc.d
  shell: "update-rc.d openhab defaults"
  sudo: yes

- name: check current timezone
  shell: cat /etc/timezone
  register: current_zone

- name: Set timezone variables
  copy: content="Europe/Oslo"
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644
    backup=yes
  sudo: yes

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
  sudo: yes

- name: Install required packages
  apt: name={{item}} state=installed
  with_items:
    - nodejs
    - npm
    - python-setuptools
  sudo: yes

- easy_install: name=speedtest-cli state=latest

- name: Install "request" node.js package.
  npm: name=request path={{openhab_install_dir}}/runtime/{{openhab_version}}/configurations/scripts

- name: Install "object-assign" node.js package.
  npm: name=object-assign path={{openhab_install_dir}}/runtime/{{openhab_version}}/configurations/scripts

- name: Install "es6-promise" node.js package.
  npm: name=es6-promise path={{openhab_install_dir}}/runtime/{{openhab_version}}/configurations/scripts